- name: Show Date
  gsettings:
    schema: org.gnome.desktop.interface
    key: clock-show-date
    value: "true"

- name: Never Auto-run Removable Media
  gsettings:
    schema: org.gnome.desktop.media-handling
    key: autorun-never
    value: "true"

- name: Close Window Shortcuts
  gsettings:
    schema: org.gnome.desktop.wm.keybindings
    key: close
    value: "['<Alt>q', '<Alt>F4']"

- name: Only Display Windows from Current Workspace in Switchers
  gsettings:
    schema: "{{ item }}"
    key: current-workspace-only
    value: "true"
  with_items:
    - org.gnome.shell.app-switcher
    - org.gnome.shell.window-switcher

- name: Automatically clean Temp/Trash files
  gsettings:
    schema: org.gnome.desktop.privacy
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - {key: remove-old-temp-files, value: "false"}   # Do not enable - Interferes with gpgagent
    - {key: remove-old-trash-files, value: "true"}
    - {key: old-files-age, value: "uint32 1"}

- name: Resize with Right button
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: resize-with-right-button
    value: "true"

- name: Move Windows with Alt Key
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: mouse-button-modifier
    value: "<Alt>"

- name: Switch Windows with Alt-Tab
  gsettings:
    schema: org.gnome.desktop.wm.keybindings
    key: switch-windows
    value: "['<Alt>Tab']"

- name: Evolution is installed
  zypper:
    name: evolution
    state: latest

- name: Display Reminders in Notification Area Only
  gsettings:
    schema: org.gnome.evolution.calendar
    key: notify-with-tray
    value: "true"

- name: Center Windows
  gsettings:
    schema: org.gnome.mutter
    key: center-new-windows
    value: "true"

- name: Focus Windows on Creation
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: focus-new-windows
    value: "strict"

- name: Remove NoDisplay from Gnome Shortcuts
  become: yes
  ini_file:
    dest: "{{ item }}"
    option: NoDisplay
    value: "false"
    section: "Desktop Entry"
  with_items:
    - "/usr/share/applications/gnome-background-panel.desktop"
    - "/usr/share/applications/gnome-bluetooth-panel.desktop"
    - "/usr/share/applications/gnome-datetime-panel.desktop"
    - "/usr/share/applications/gnome-display-panel.desktop"
    - "/usr/share/applications/gnome-keyboard-panel.desktop"
    - "/usr/share/applications/gnome-mouse-panel.desktop"
    - "/usr/share/applications/gnome-network-panel.desktop"
    - "/usr/share/applications/gnome-power-panel.desktop"
    - "/usr/share/applications/gnome-printers-panel.desktop"
    - "/usr/share/applications/gnome-privacy-panel.desktop"
    - "/usr/share/applications/gnome-sound-panel.desktop"
    - "/usr/share/applications/gnome-user-accounts-panel.desktop"
