---

- name: Suspend on Battery
  gsettings:
    schema: org.gnome.settings-daemon.plugins.power
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - {key: sleep-inactive-battery-type, value: suspend}
    - {key: sleep-inactive-battery-timeout, value: 900}  # 15min
