---

- name: flatpak and dependencies is installed
  become: "yes"
  zypper:
    name: "{{ item }}"
  loop:
    - flatpak
    - xdg-desktop-portal-gtk

- name: Flathub Remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
  # Don't run this task if running inside a docker container (e.g. CircleCI)
  when: dockerenv.stat.exists == False

- name: Flatpak Apps Installed
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_apps }}"
  # Don't run this task if running inside a docker container (e.g. CircleCI)
  when: dockerenv.stat.exists == False
