- name: Install Atom
  become: yes
  zypper:
    # Ideally would use https://atom.io/download/rpm but zypper does not handle the redirect
    name: "https://github.com/atom/atom/releases/download/v1.17.0/atom.x86_64.rpm"
    state: present

- name: Setup Atom Packages
  apm:
    name: "{{ item }}"
  with_items:
    - atom-beautify
    - atom-dark-fusion-syntax
    - atom-jinja2
    - atom-material-syntax
    - autocomplete-python
    - better-window-title
    - blame
    - color-picker
    - copy-tools
    - dash
    - file-icons
    - firewatch-syntax
    - git-time-machine
    - highlight-selected
    - hyperclick
    - keybinding-cheatsheet
    - language-babel
    - language-d
    - language-docker
    - language-protobuf
    - language-r
    - language-restructuredtext
    - language-swift
    - language-vala
    - last-cursor-position
    - linter
    - linter-flake8
    - linter-shellcheck
    - nucleus-dark-ui
    - pdf-view
    - pigments
    - python-isort
    - python-tools
    - sort-lines
    - tab-title
    - vim-mode

- name: Setup Atom configuration
  file:
    dest: "{{ item.dest }}"
    force: yes
    state: link
    src: "{{ item.src }}"
  with_items:
    - {src: "{{ ansible_env.PWD }}/roles/atom/files/atom_config.cson", dest: ~/.atom/config.cson}
    - {src: "{{ ansible_env.PWD }}/roles/atom/files/atom_keymap.cson", dest: ~/.atom/keymap.cson}
    - {src: "{{ ansible_env.PWD }}/roles/atom/files/atom_snippets.cson", dest: ~/.atom/snippets.cson}
    - {src: "{{ ansible_env.PWD }}/roles/atom/files/atom_init.js", dest: ~/.atom/init.js}
    - {src: "{{ ansible_env.PWD }}/roles/atom/files/atom_styles.less", dest: ~/.atom/styles.less}
