---

repos:
  # zypper_repository bug means that you cannot link to .repo uris.
  # See https://github.com/ansible/ansible/issues/23257

  - uri: https://download.opensuse.org/repositories/home:/MichaelAquilina/openSUSE_Tumbleweed/
    name: MichaelAquilina

  - uri:
      "http://download.opensuse.org/repositories/devel:/openSUSE:/Factory:/Apps/openSUSE_Tumbleweed/"
    name: Apps

gnome_apps:
  - dconf-editor
  - flatpak
  - xdg-desktop-portal-gtk  # required for opening links etc..
  - gthumb
  - meld
  - notes-up
  - rhythmbox
  - quickdocs
  - synapse
  - tilix
